openapi: 3.0.1
info:
  title: shiharaikun
  description: ''
  version: 1.0.0
tags: []
paths:
  /invoices:
    get:
      summary: 請求書データ取得
      deprecated: false
      description: ''
      tags: []
      parameters:
        - name: start_date
          in: query
          description: ''
          required: false
          schema:
            type: string
        - name: end_date
          in: query
          description: ''
          required: false
          schema:
            type: string
        - name: X-Tenant-ID
          in: header
          description: ''
          required: false
          example: ''
          schema:
            type: string
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  invoices:
                    type: array
                    items: &ref_0
                      $ref: '#/components/schemas/invoice'
                required:
                  - invoices
      security: []
    post:
      summary: 請求書データ登録
      deprecated: false
      description: ''
      tags: []
      parameters:
        - name: X-Tenant-ID
          in: header
          description: ''
          required: false
          example: ''
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                issueDate:
                  type: string
                  format: date
                amountDue:
                  type: integer
                taxRatePercent:
                  type: integer
                dueDate:
                  type: string
                  format: date
              required:
                - issueDate
                - amountDue
                - taxRatePercent
                - dueDate
      responses:
        '201':
          description: 作成済み
          content:
            application/json:
              schema:
                type: object
                properties:
                  invoice: *ref_0
                required:
                  - invoice
      security: []
components:
  schemas:
    invoice:
      type: object
      properties:
        issueDate:
          type: string
          format: date
        amountDue:
          type: integer
        fee:
          type: integer
        feeRatePercent:
          type: integer
        Tax:
          type: integer
        taxRatePercent:
          type: integer
        totalAmount:
          type: integer
        dueDate:
          type: string
          format: date
        status:
          type: string
          enum:
            - Pending
            - InProcess
            - Paid
            - Error
      required:
        - issueDate
        - fee
        - feeRatePercent
        - Tax
        - taxRatePercent
        - totalAmount
        - dueDate
        - status
        - amountDue
  securitySchemes: {}
servers: []
